### ISSUE TITLE
typescript 4.1 support

### ISSUE THREAD

**Issue by simllll** [lukeautry/tserial#5]
it's not working with the new typescript 4.1 feature of [template literal types ](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types).

when used it throws errors like ...d.ts:114:106 - error TS1110: Type expected.
